$.tablesorter.themes.bootstrap = {
  table: 'table'
  caption: 'caption'
  header: ''
  sortNone: ''
  sortAsc: ''
  sortDesc: ''
  active: ''
  hover: ''
  icons: ''
  iconSortNone: 'fa fa-sort'
  iconSortAsc: 'fa fa-sort-asc'
  iconSortDesc: 'fa fa-sort-desc'
  filterRow: ''
  footerRow: ''
  footerCells: ''
  even: ''
  odd: ''
}
