#encoding: utf-8

class Store < ActiveRecord::Base

  store :settings, accessors: [
    :locale,   # see #locale_options for supported locales
    :theme,    # see app/stylesheets/spry_themes
    :brand_image, # additional branding image displayed in the footer
    :masonry, # boolean, use masonry in storefront products view
    :inline_iframes,  # boolean, render iframes inline (instead of popups)
    :card_image_type, # image purpose to use for cover images on cards etc.
    :list_image_type, # image purpose in list views
    :allow_shopping,  # boolean, master switch to allow/disallow shopping
    :b2b_sales,       # boolean, does the shop do business to business sales
    :admit_guests,    # boolean, are guests allowed to shop at the store
    :shipping_cost_product_id,  # product reference for shipping cost
    :free_shipping_at,  # order total beyond which shipping cost won't apply
    :tracking_code,   # Google Analytics code
    :tawkto_site_id, # tawk.to site id for chat widget
    :pbw_api_key,     # Paybyway API key
    :pbw_private_key, # Paybyway private key
    :order_sequence, # base value for order numbers if no numbering exists
    :manufacturer_template_id, # page references to templates
    :reseller_template_id,
    :quotation_template_id,
    :csv_encoding,        # CSV encoding of uploaded files
    :csv_product_code,    # CSV field headers for product code,
    :csv_retail_price,    # retail price, and inventory amount
    :csv_inventory_amount # in uploaded files
  ], coder: JSON

  resourcify
  include Authority::Abilities
  include Imageable

  #---
  after_create :assign_slug

  #---
  # A store may appear at multiple portals.
  has_and_belongs_to_many :portals

  # All these associations are dependent of the store.
  with_options dependent: :destroy do |store|
    store.has_many :inventories
    store.has_many :categories
    store.has_many :products
    store.has_many :properties
    store.has_many :orders
    store.has_many :order_types
    store.has_many :shipping_methods
    store.has_many :pages
    store.has_many :albums
    store.has_many :promotions
    store.has_many :users
    store.has_many :customer_assets
    store.has_many :pricing_groups
  end

  has_many :inventory_items, through: :inventories

  accepts_nested_attributes_for :users, limit: 1

  scope :all_except, -> (this) { where.not(id: this) }

  #---
  validates :name, presence: true
  validates :host, presence: true, uniqueness: true
  validates :subdomain, uniqueness: true, allow_blank: true
  validates :erp_number, numericality: true, allow_blank: true

  #---
  # The minimal set of default settings for a newly created store.
  def self.default_settings
    {
      brand_image: 'leasit.svg',
      card_image_type: 'presentational',
      list_image_type: 'presentational'
    }
  end

  def self.locale_options
    @@locale_options ||= [['English', 'en'], ['Deutsch', 'de'], ['suomi', 'fi']]
  end

  # Looks up the names of precompiled stylesheets for themes.
  def self.theme_options
    @@themes ||= Rails.application.config.assets.precompile.select { |a|
      a.is_a?(String) && a.sub!(/spry_themes\/([^.]+)\.css/, "\\1")
    }
  end

  #---
  # Defaults for guest users reveal pricing and will allow shopping
  # if admit_guests is also enabled, to get in without authentication.
  def guest_user_defaults
    name = "#{Time.now.to_i}#{rand(100)}"
    {
      name: name,
      email: "#{name}@#{host}",
      group: User.groups[:guest],
      roles: Role.where(name: 'see_pricing')
    }
  end

  # Performs an inventory valuation of live products on hand.
  def inventory_valuation
    items = inventory_items.joins(:product).merge(Product.live)
    [items, items.map { |item| item.total_value }.sum]
  end

  # Properties flagged searchable.
  def searchable_properties
    properties.merge(Property.searchable).merge(Property.sorted)
  end

  # Available categories at top level.
  def top_level_category_options(exclude = nil)
    (categories.top_level - [exclude]).map { |c| [c.name, c.id] }
  end

  def user_options
    users.map { |u| [u.to_s, u.id] }
  end

  def album_options
    albums.map { |a| [a.to_s, a.id] }
  end

  def template_options
    pages.template.map { |p| [p.to_s, p.id] }
  end

  # Finds the shipping cost product manually due to having
  # shipping_cost_product_id a setting instead of a real relation.
  def shipping_cost_product
    if shipping_cost_product_id.present?
      Product.find(shipping_cost_product_id)
    else
      nil
    end
  end

  # Defines accessors to boolean settings not generated by Rails.
  %w[masonry inline_iframes allow_shopping admit_guests b2b_sales].each do |method|
    alias_method "#{method}?", method
    define_method("#{method}=") do |value|
      super(['1', 1, true].include?(value))
    end
  end

  def correspondents
    users.with_role(:correspondence)
  end

  # Serves the contents of the letterhead template for given user.
  def letterhead(user)
    page_id = send("#{user.group}_template_id")
    return '' unless page_id.present?
    pages.find(page_id).content
  end

  # Quotation boilerplate is the template page contents.
  def quotation_boilerplate
    return '' unless quotation_template_id.present?
    pages.find(quotation_template_id).content
  end

  # CSV header conversion table for uploaded products.
  def csv_headers
    {
      csv_product_code => :product_code,
      csv_retail_price => :retail_price,
      csv_inventory_amount => :inventory_amount
    }
  end

  def csv_options
    {
      col_sep: ';',
      encoding: csv_encoding || 'utf-8',
      headers: true
    }
  end

  def to_s
    name
  end

  def description
    nil
  end

  private
    def assign_slug
      taken_slugs = Store.all_except(self).map(&:slug)
      len = 3
      unique_slug = "#{name}#{id}#{Time.now.to_i}"
        .parameterize.underscore.mb_chars.downcase
      begin
        slug = unique_slug[0, len]
        len += 1
      end while taken_slugs.include?(slug)
      update(slug: slug)
    end
end
